
BG_MENU = "assets/images/bg_menu.jpg"
THEME_IMG = "assets/images/theme.png"
BUTTON_IMG = "assets/images/button.png"


NROWS = 36
NCOLS = 28
TILEWIDTH = 16
TILEHEIGHT = 16
SCREENWIDTH = NCOLS*TILEWIDTH
SCREENHEIGHT = NROWS*TILEHEIGHT
SCREENSIZE = (SCREENWIDTH + 350, SCREENHEIGHT)
PANEL_WIDTH = 200 
